// Generated by jextract

package org.unix;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
public class __sbuf {

    static final  GroupLayout $struct$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_POINTER$LAYOUT.withName("_base"),
        Constants$root.C_INT$LAYOUT.withName("_size"),
        MemoryLayout.paddingLayout(32)
    ).withName("__sbuf");
    public static MemoryLayout $LAYOUT() {
        return __sbuf.$struct$LAYOUT;
    }
    static final VarHandle _base$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("_base"));
    public static VarHandle _base$VH() {
        return __sbuf._base$VH;
    }
    public static MemoryAddress _base$get(MemorySegment seg) {
        return (java.lang.foreign.MemoryAddress)__sbuf._base$VH.get(seg);
    }
    public static void _base$set( MemorySegment seg, MemoryAddress x) {
        __sbuf._base$VH.set(seg, x);
    }
    public static MemoryAddress _base$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemoryAddress)__sbuf._base$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void _base$set(MemorySegment seg, long index, MemoryAddress x) {
        __sbuf._base$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle _size$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("_size"));
    public static VarHandle _size$VH() {
        return __sbuf._size$VH;
    }
    public static int _size$get(MemorySegment seg) {
        return (int)__sbuf._size$VH.get(seg);
    }
    public static void _size$set( MemorySegment seg, int x) {
        __sbuf._size$VH.set(seg, x);
    }
    public static int _size$get(MemorySegment seg, long index) {
        return (int)__sbuf._size$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void _size$set(MemorySegment seg, long index, int x) {
        __sbuf._size$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(int len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemoryAddress addr, MemorySession session) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, session); }
}


