// Generated by jextract

package org.unix;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$44 {

    static final FunctionDescriptor mkostemp$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle mkostemp$MH = RuntimeHelper.downcallHandle(
        "mkostemp",
        constants$44.mkostemp$FUNC
    );
    static final FunctionDescriptor mkostemps$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle mkostemps$MH = RuntimeHelper.downcallHandle(
        "mkostemps",
        constants$44.mkostemps$FUNC
    );
    static final FunctionDescriptor mkstemp_dprotected_np$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle mkstemp_dprotected_np$MH = RuntimeHelper.downcallHandle(
        "mkstemp_dprotected_np",
        constants$44.mkstemp_dprotected_np$FUNC
    );
    static final FunctionDescriptor mkdtempat_np$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle mkdtempat_np$MH = RuntimeHelper.downcallHandle(
        "mkdtempat_np",
        constants$44.mkdtempat_np$FUNC
    );
    static final FunctionDescriptor mkstempsat_np$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle mkstempsat_np$MH = RuntimeHelper.downcallHandle(
        "mkstempsat_np",
        constants$44.mkstempsat_np$FUNC
    );
    static final FunctionDescriptor mkostempsat_np$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle mkostempsat_np$MH = RuntimeHelper.downcallHandle(
        "mkostempsat_np",
        constants$44.mkostempsat_np$FUNC
    );
}


