// Generated by jextract

package org.unix;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$41 {

    static final FunctionDescriptor fflagstostr$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle fflagstostr$MH = RuntimeHelper.downcallHandle(
        "fflagstostr",
        constants$41.fflagstostr$FUNC
    );
    static final FunctionDescriptor getdomainname$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle getdomainname$MH = RuntimeHelper.downcallHandle(
        "getdomainname",
        constants$41.getdomainname$FUNC
    );
    static final FunctionDescriptor getgrouplist$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle getgrouplist$MH = RuntimeHelper.downcallHandle(
        "getgrouplist",
        constants$41.getgrouplist$FUNC
    );
    static final FunctionDescriptor gethostuuid$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gethostuuid$MH = RuntimeHelper.downcallHandle(
        "gethostuuid",
        constants$41.gethostuuid$FUNC
    );
    static final FunctionDescriptor getmode$FUNC = FunctionDescriptor.of(Constants$root.C_SHORT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_SHORT$LAYOUT
    );
    static final MethodHandle getmode$MH = RuntimeHelper.downcallHandle(
        "getmode",
        constants$41.getmode$FUNC
    );
    static final FunctionDescriptor getpeereid$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle getpeereid$MH = RuntimeHelper.downcallHandle(
        "getpeereid",
        constants$41.getpeereid$FUNC
    );
}


