// Generated by jextract

package org.unix;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$9 {

    static final FunctionDescriptor __swbuf$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle __swbuf$MH = RuntimeHelper.downcallHandle(
        "__swbuf",
        constants$9.__swbuf$FUNC
    );
    static final FunctionDescriptor __sputc$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle __sputc$MH = RuntimeHelper.downcallHandle(
        "__sputc",
        constants$9.__sputc$FUNC
    );
    static final FunctionDescriptor flockfile$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle flockfile$MH = RuntimeHelper.downcallHandle(
        "flockfile",
        constants$9.flockfile$FUNC
    );
    static final FunctionDescriptor ftrylockfile$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle ftrylockfile$MH = RuntimeHelper.downcallHandle(
        "ftrylockfile",
        constants$9.ftrylockfile$FUNC
    );
    static final FunctionDescriptor funlockfile$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle funlockfile$MH = RuntimeHelper.downcallHandle(
        "funlockfile",
        constants$9.funlockfile$FUNC
    );
    static final FunctionDescriptor getc_unlocked$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle getc_unlocked$MH = RuntimeHelper.downcallHandle(
        "getc_unlocked",
        constants$9.getc_unlocked$FUNC
    );
}


