// Generated by jextract

package org.unix;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$46 {

    static final FunctionDescriptor rcmd$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle rcmd$MH = RuntimeHelper.downcallHandle(
        "rcmd",
        constants$46.rcmd$FUNC
    );
    static final FunctionDescriptor rcmd_af$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle rcmd_af$MH = RuntimeHelper.downcallHandle(
        "rcmd_af",
        constants$46.rcmd_af$FUNC
    );
    static final FunctionDescriptor rresvport$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle rresvport$MH = RuntimeHelper.downcallHandle(
        "rresvport",
        constants$46.rresvport$FUNC
    );
    static final FunctionDescriptor rresvport_af$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle rresvport_af$MH = RuntimeHelper.downcallHandle(
        "rresvport_af",
        constants$46.rresvport_af$FUNC
    );
    static final FunctionDescriptor iruserok$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle iruserok$MH = RuntimeHelper.downcallHandle(
        "iruserok",
        constants$46.iruserok$FUNC
    );
    static final FunctionDescriptor iruserok_sa$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle iruserok_sa$MH = RuntimeHelper.downcallHandle(
        "iruserok_sa",
        constants$46.iruserok_sa$FUNC
    );
}


