// Generated by jextract

package org.unix;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$48 {

    static final FunctionDescriptor setlogin$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle setlogin$MH = RuntimeHelper.downcallHandle(
        "setlogin",
        constants$48.setlogin$FUNC
    );
    static final FunctionDescriptor setmode$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle setmode$MH = RuntimeHelper.downcallHandle(
        "setmode",
        constants$48.setmode$FUNC
    );
    static final FunctionDescriptor setrgid$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle setrgid$MH = RuntimeHelper.downcallHandle(
        "setrgid",
        constants$48.setrgid$FUNC
    );
    static final FunctionDescriptor setruid$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle setruid$MH = RuntimeHelper.downcallHandle(
        "setruid",
        constants$48.setruid$FUNC
    );
    static final FunctionDescriptor setsgroups_np$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle setsgroups_np$MH = RuntimeHelper.downcallHandle(
        "setsgroups_np",
        constants$48.setsgroups_np$FUNC
    );
    static final FunctionDescriptor setusershell$FUNC = FunctionDescriptor.ofVoid();
    static final MethodHandle setusershell$MH = RuntimeHelper.downcallHandle(
        "setusershell",
        constants$48.setusershell$FUNC
    );
}


