// Generated by jextract

package org.unix;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$45 {

    static final FunctionDescriptor nfssvc$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle nfssvc$MH = RuntimeHelper.downcallHandle(
        "nfssvc",
        constants$45.nfssvc$FUNC
    );
    static final FunctionDescriptor profil$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle profil$MH = RuntimeHelper.downcallHandle(
        "profil",
        constants$45.profil$FUNC
    );
    static final FunctionDescriptor pthread_setugid_np$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle pthread_setugid_np$MH = RuntimeHelper.downcallHandle(
        "pthread_setugid_np",
        constants$45.pthread_setugid_np$FUNC
    );
    static final FunctionDescriptor pthread_getugid_np$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle pthread_getugid_np$MH = RuntimeHelper.downcallHandle(
        "pthread_getugid_np",
        constants$45.pthread_getugid_np$FUNC
    );
    static final FunctionDescriptor reboot$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle reboot$MH = RuntimeHelper.downcallHandle(
        "reboot",
        constants$45.reboot$FUNC
    );
    static final FunctionDescriptor revoke$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle revoke$MH = RuntimeHelper.downcallHandle(
        "revoke",
        constants$45.revoke$FUNC
    );
}


