// Generated by jextract

package org.unix;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$23 {

    static final FunctionDescriptor __darwin_fd_isset$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle __darwin_fd_isset$MH = RuntimeHelper.downcallHandle(
        "__darwin_fd_isset",
        constants$23.__darwin_fd_isset$FUNC
    );
    static final FunctionDescriptor __darwin_fd_set$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle __darwin_fd_set$MH = RuntimeHelper.downcallHandle(
        "__darwin_fd_set",
        constants$23.__darwin_fd_set$FUNC
    );
    static final FunctionDescriptor __darwin_fd_clr$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle __darwin_fd_clr$MH = RuntimeHelper.downcallHandle(
        "__darwin_fd_clr",
        constants$23.__darwin_fd_clr$FUNC
    );
    static final FunctionDescriptor getattrlistbulk$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle getattrlistbulk$MH = RuntimeHelper.downcallHandle(
        "getattrlistbulk",
        constants$23.getattrlistbulk$FUNC
    );
    static final FunctionDescriptor getattrlistat$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle getattrlistat$MH = RuntimeHelper.downcallHandle(
        "getattrlistat",
        constants$23.getattrlistat$FUNC
    );
    static final FunctionDescriptor setattrlistat$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle setattrlistat$MH = RuntimeHelper.downcallHandle(
        "setattrlistat",
        constants$23.setattrlistat$FUNC
    );
}


