// Generated by jextract

package org.unix;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$13 {

    static final FunctionDescriptor open_memstream$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle open_memstream$MH = RuntimeHelper.downcallHandle(
        "open_memstream",
        constants$13.open_memstream$FUNC
    );
    static final  OfInt sys_nerr$LAYOUT = Constants$root.C_INT$LAYOUT;
    static final VarHandle sys_nerr$VH = constants$13.sys_nerr$LAYOUT.varHandle();
    static final MemorySegment sys_nerr$SEGMENT = RuntimeHelper.lookupGlobalVariable("sys_nerr", constants$13.sys_nerr$LAYOUT);
    static final FunctionDescriptor asprintf$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle asprintf$MH = RuntimeHelper.downcallHandleVariadic(
        "asprintf",
        constants$13.asprintf$FUNC
    );
    static final FunctionDescriptor ctermid_r$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle ctermid_r$MH = RuntimeHelper.downcallHandle(
        "ctermid_r",
        constants$13.ctermid_r$FUNC
    );
    static final FunctionDescriptor fgetln$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle fgetln$MH = RuntimeHelper.downcallHandle(
        "fgetln",
        constants$13.fgetln$FUNC
    );
}


