// Generated by jextract

package org.unix;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$16 {

    static final FunctionDescriptor funopen$x3$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle funopen$x3$MH = RuntimeHelper.downcallHandle(
        constants$16.funopen$x3$FUNC
    );
    static final FunctionDescriptor funopen$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle funopen$MH = RuntimeHelper.downcallHandle(
        "funopen",
        constants$16.funopen$FUNC
    );
    static final FunctionDescriptor __sprintf_chk$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle __sprintf_chk$MH = RuntimeHelper.downcallHandleVariadic(
        "__sprintf_chk",
        constants$16.__sprintf_chk$FUNC
    );
    static final FunctionDescriptor __snprintf_chk$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle __snprintf_chk$MH = RuntimeHelper.downcallHandleVariadic(
        "__snprintf_chk",
        constants$16.__snprintf_chk$FUNC
    );
    static final FunctionDescriptor __vsprintf_chk$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle __vsprintf_chk$MH = RuntimeHelper.downcallHandle(
        "__vsprintf_chk",
        constants$16.__vsprintf_chk$FUNC
    );
    static final FunctionDescriptor __vsnprintf_chk$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle __vsnprintf_chk$MH = RuntimeHelper.downcallHandle(
        "__vsnprintf_chk",
        constants$16.__vsnprintf_chk$FUNC
    );
}


