// Generated by jextract

package org.unix;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
public interface funopen$x3 {

    int apply(java.lang.foreign.MemoryAddress _x0);
    static MemorySegment allocate(funopen$x3 fi, MemorySession session) {
        return RuntimeHelper.upcallStub(funopen$x3.class, fi, constants$15.funopen$x3$FUNC, session);
    }
    static funopen$x3 ofAddress(MemoryAddress addr, MemorySession session) {
        MemorySegment symbol = MemorySegment.ofAddress(addr, 0, session);
        return (java.lang.foreign.MemoryAddress __x0) -> {
            try {
                return (int)constants$16.funopen$x3$MH.invokeExact((Addressable)symbol, (java.lang.foreign.Addressable)__x0);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


